export * from './Search';

export enum ApiType {
    Search = 'Search',
    SearchTitle = 'SearchTitle',
    SearchMovie = 'SearchMovie',
    SearchSeries = 'SearchSeries',
    SearchName = 'SearchName',
    SearchEpisode = 'SearchEpisode',
    SearchCompany = 'SearchCompany',
    SearchKeyword = 'SearchKeyword',
    SearchAll = 'SearchAll',
    Title = 'Title',
    Report = 'Report',
    FullCast = 'FullCast',
    Posters = 'Posters',
    Images = 'Images',
    Trailer = 'Trailer',
    Ratings = 'Ratings',
    UserRatings = 'UserRatings',
    SeasonEpisodes = 'SeasonEpisodes',
    ExternalSites = 'ExternalSites',
    Wikipedia = 'Wikipedia',
    IMDbList = 'IMDbList',
    Reviews = 'Reviews',
    MetacriticReviews = 'MetacriticReviews',
    FAQ = 'FAQ',
    Top250Movies = 'Top250Movies',
    Top250TVs = 'Top250TVs',
    MostPopularMovies = 'MostPopularMovies',
    MostPopularTVs = 'MostPopularTVs',
    InTheaters = 'InTheaters',
    ComingSoon = 'ComingSoon',
    BoxOffice = 'BoxOffice',
    BoxOfficeAllTime = 'BoxOfficeAllTime',
    Name = 'Name',
    Company = 'Company',
    Keyword = 'Keyword',
    YouTubeTrailer = 'YouTubeTrailer',
    YouTube = 'YouTube',
    YouTubePlaylist = 'YouTubePlaylist'
}