// Generated by https://quicktype.io
// Generated from `/static/api/title/find/q=Avengers.json`

export interface Response {
    "@meta": Meta;
    "@type": string;
    query: string;
    results: Result[];
    types: string[];
}

export interface Meta {
    operation: string;
    requestId: string;
    serviceTimeMs: number;
}

export interface Result {
    id: string;
    image?: Image;
    runningTimeInMinutes?: number;
    title?: string;
    titleType?: TitleType;
    year?: number;
    principals?: Principal[];
    nextEpisode?: string;
    numberOfEpisodes?: number;
    seriesEndYear?: number;
    seriesStartYear?: number;
    legacyNameText?: string;
    name?: string;
    knownFor?: KnownFor[];
    akas?: string[];
    disambiguation?: string;
}

export interface Image {
    height: number;
    id: string;
    url: string;
    width: number;
}

export interface KnownFor {
    crew?: Crew[];
    summary: Summary;
    id: string;
    title: string;
    titleType: TitleType;
    year: number;
    cast?: Cast[];
}

export interface Cast {
    billing?: number;
    category: Category;
    characters: string[];
    roles: Role[];
    endYear?: number;
    episodeCount?: number;
    startYear?: number;
}

export enum Category {
    Actor = "actor",
    Actress = "actress",
    Self = "self",
}

export interface Role {
    character: string;
    characterId?: string;
}

export interface Crew {
    category: string;
    job?: string;
}

export interface Summary {
    category: string;
    displayYear?: string;
    characters?: string[];
}

export enum TitleType {
    Movie = "movie",
    MusicVideo = "musicVideo",
    TvSeries = "tvSeries",
    VideoGame = "videoGame",
}

export interface Principal {
    id: string;
    legacyNameText: string;
    name: string;
    billing?: number;
    category: Category;
    characters: string[];
    roles: Role[];
    disambiguation?: string;
    attr?: string[];
    endYear?: number;
    episodeCount?: number;
    startYear?: number;
}
