# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: "Build CodersCamp2021 App with tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        if: always()
        with:
          name: movieAppDist
          path: ./dist
